[[redirects]]
  from = "/hotels"
  to = "https://bookingwebsite-vhgs.onrender.com/api/hotels"
  status = 200
  force = true

[[redirects]]
  from = "/hotels/countByCity"
  to = "https://bookingwebsite-vhgs.onrender.com/api/hotels/countByCity"
  status = 200
  force = true